
jobs:
 - name: daily
   targetName: dev 
   schedule: 0 12 * * * 
   
   steps:
     - name: run models 
       command: dbt run -m stg_orders 
     - name: test models
       command: dbt test -m stg_orders 

 - name: nightly
   schedule: 0 0 * * * 
   steps:
     - name: run models
       command: dbt run 

